### ISSUE TITLE
Green arrow is not showing as big as before and it's not italics font

### ISSUE THREAD

**Issue by tianliu3** [dracula/iterm#11]
Left is Terminal right side is Iterm2
![image](https://user-images.githubusercontent.com/55416011/83602232-01c1b100-a527-11ea-9f90-a0cd80230274.png)

**Comment by Glennmen** [comment]
The left one (terminal) has a more bold font it seems. Did you try changing to the same font?

**Comment by tianliu3** [comment]
> The left one (terminal) has a more bold font it seems. Did you try changing to the same font?

Thanks for pointing out. The font actually different left one has font SF mono.
