### ISSUE TITLE
Nothing change when imported

### ISSUE THREAD

**Issue by Piero87** [dracula/iterm#3]
Hi,
I have added the color to iTerm, but change only the background as you can see:

<img width="1171" alt="schermata 2017-06-12 alle 23 53 17" src="https://user-images.githubusercontent.com/768952/27056945-5bdbe242-4fca-11e7-8166-dbf868e748fd.png">

**Comment by dambridge** [comment]
Same issue here.

**Comment by seagle0128** [comment]
@all You need to enable the color theme in the profiles after importing. Select it in `Color Presets`.

**Comment by matewilk** [comment]
Same here, nothing changes after applying the theme and I'm 100% sure I did all according to the instructions. Iterm version `iTerm2 3.0.15`

**Comment by viniciusntch** [comment]
Me too..nothing happened

**Comment by maxdahinten** [comment]
What is up here? Did the status changed? Have the same Problem....Just Background change :/

**Comment by wenindoubt** [comment]
Do you guys also have the following installed on your ZSH? https://github.com/dracula/zsh

**Comment by Piero87** [comment]
Nope

**Comment by zenorocha** [comment]
That's not included on the iTerm theme. You'll need the [Dracula ZSH theme](https://github.com/dracula/zsh) for those kind of functionalities.

**Comment by an00bhav** [comment]
Or on bash, you can install this:
https://github.com/magicmonty/bash-git-prompt
