### ISSUE TITLE
UI seems a little diffrent with the official screenshot

### ISSUE THREAD

**Issue by imjustfly** [dracula/iterm#5]
<img width="1148" alt="screen shot 2017-11-01 at 21 50 06" src="https://user-images.githubusercontent.com/2912764/32277820-aa27a172-bf4e-11e7-96fc-f3fd76da5a08.png">

the command and strings  still have no color. But the official screenshot shows the command should green and string should be yellow.

I used dracula theme for  iterm2 and zsh. I missed something?

**Comment by mirandashort** [comment]
Same here - no colors at all

**Comment by inflation** [comment]
Same here, I'm on `fish`

**Comment by paxton4444** [comment]
same here, no arrows, or colors. Not sure how I can make it look like that.

**Comment by an00bhav** [comment]
Seems like thats more of a bash prompt configuration. 

Have a look at this 
https://github.com/magicmonty/bash-git-prompt

**Comment by aizkhaj** [comment]
I've figured this out.

That syntax highlighting is coming from a plugin called `zsh-syntax-highlighting`. As it may be obvious to some, it relies on zsh and not bash. Instructions to installing the plugin are on their repo at: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md.

If you use homebrew to install this plugin, make sure you add the line it asks you to add into your .zshrc file.

**Comment by imjustfly** [comment]
@aizkhaj thanks a lot!
