### ISSUE TITLE
Not Showing up completely , only background changed

### ISSUE THREAD

**Issue by droid-lover** [dracula/iterm#7]
I followed all these steps :- 

iTerm2 > Preferences > Profiles > Colors Tab
Open the Color Presets... drop-down in the bottom right corner
Select Import... from the list
Select the Dracula.itermcolors file
Select the Dracula from Color Presets.

But only background is changed , other path  or branch names is still in default white color , not able to see as shown in screenshot completely .

**Comment by zenorocha** [comment]
That's not included on the iTerm theme. You'll need the [Dracula ZSH theme](https://github.com/dracula/zsh) for those kind of functionalities.
